import 'server-only';

import { prisma } from '@mungsan/db';
import type { DB } from '@mungsan/db';

// 현재 유저의 자산 리포트 — reportDate 최신순. canonical 값만 반환(Date·enum·number),
// KST 날짜·파일크기 등 표시 변환은 ui가 담당.
export type ManageAssetReportView = {
  id: string;
  type: DB.AssetReportType;
  title: string;
  autoGenerated: boolean;
  reportDate: Date;
  fileSizeBytes: number;
};

// fileName 은 다운로드 버튼 문구 교체(2026-07-23) 이후 화면 어디에도 안 쓰여 select 에서 제외
// (스키마 컬럼은 유지 — 리포트 실생성 기획 시 재사용).
export async function getManageAssetReportsQuery(
  userId: string,
): Promise<ManageAssetReportView[]> {
  return prisma.assetReport.findMany({
    where: { userId },
    orderBy: { reportDate: 'desc' },
    select: {
      id: true,
      type: true,
      title: true,
      autoGenerated: true,
      reportDate: true,
      fileSizeBytes: true,
    },
  });
}
