import 'server-only';

import { prisma } from '@mungsan/db';
import type { DB } from '@mungsan/db';

// 현재 유저의 자산 리포트 — reportDate 최신순. canonical 값만 반환(Date·enum·number),
// KST 날짜·파일크기 등 표시 변환은 ui가 담당.
export type ManageAssetReportView = {
  id: string;
  type: DB.AssetReportType;
  title: string;
  autoGenerated: boolean;
  reportDate: Date;
  fileName: string;
  fileSizeBytes: number;
};

export async function getManageAssetReportsQuery(
  userId: string,
): Promise<ManageAssetReportView[]> {
  return prisma.assetReport.findMany({
    where: { userId },
    orderBy: { reportDate: 'desc' },
    select: {
      id: true,
      type: true,
      title: true,
      autoGenerated: true,
      reportDate: true,
      fileName: true,
      fileSizeBytes: true,
    },
  });
}
