// 비즈니스 관리 화면 목 데이터 — UI 레벨 전용(DB/스키마 없음).

export type TrustMetric = {
  label: string;
  value: number;
  max: number;
  tone: 'success' | 'danger';
};

export type TrustScore = {
  score: number;
  max: number;
  metrics: TrustMetric[];
  rankLabel: string;
  deltaLabel: string;
};

export type ProposalStatus = 'viewed' | 'unread' | 'replied';

export type Proposal = {
  id: string;
  company: string;
  title: string;
  sentLabel: string;
  status: ProposalStatus;
};

export type AssetType = '회고 리포트' | '정산 서류' | '계약서';

export type AssetReport = {
  id: string;
  type: AssetType;
  autoGenerated: boolean;
  title: string;
  dateLabel: string;
  size: string;
};

export const trustScore: TrustScore = {
  score: 92,
  max: 100,
  metrics: [
    { label: '협업 이행률', value: 96, max: 100, tone: 'success' },
    { label: '파트너 평가', value: 48, max: 50, tone: 'success' },
    { label: '정산 정확도', value: 19, max: 20, tone: 'success' },
    { label: '보안 준수', value: 18, max: 20, tone: 'success' },
    { label: '응답 속도', value: 9, max: 10, tone: 'danger' },
  ],
  rankLabel: '상위 8% · 신뢰 우수 등급',
  deltaLabel: '지난 달 대비 +3점',
};

export const proposals: Proposal[] = [
  {
    id: 'p1',
    company: '넥스트에이아이',
    title: 'AI 자동화 솔루션 협업 제안',
    sentLabel: '4월 12일',
    status: 'viewed',
  },
  {
    id: 'p2',
    company: '블루오션코퍼레이션',
    title: '물류 데이터 공유 파트너십 제안',
    sentLabel: '4월 10일',
    status: 'unread',
  },
  {
    id: 'p3',
    company: '메디이노베이션',
    title: '의료 AI 공동 R&D 협약 제안',
    sentLabel: '4월 8일',
    status: 'replied',
  },
];

export const assetReports: AssetReport[] = [
  {
    id: 'a1',
    type: '회고 리포트',
    autoGenerated: true,
    title: '그린랩스 협업 최종 회고',
    dateLabel: '2026.03.31',
    size: '2.4MB',
  },
  {
    id: 'a2',
    type: '정산 서류',
    autoGenerated: true,
    title: '테크브릿지 2분기 정산 명세서',
    dateLabel: '2026.04.01',
    size: '1.1MB',
  },
  {
    id: 'a3',
    type: '계약서',
    autoGenerated: false,
    title: '루나소프트 API 이용 계약서',
    dateLabel: '2026.02.15',
    size: '0.8MB',
  },
  {
    id: 'a4',
    type: '회고 리포트',
    autoGenerated: true,
    title: '핀라이트 파일럿 성과 분석',
    dateLabel: '2026.01.20',
    size: '3.2MB',
  },
];
