import { LuClock, LuDownload, LuFileText, LuShield } from 'react-icons/lu';

import { SectionHeader } from '@/components/section-header';
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';

import type { AssetReport } from '../mock';

interface AssetReportSectionProps {
  reports: AssetReport[];
}

export const AssetReportSection = ({ reports }: AssetReportSectionProps) => {
  return (
    <section className="px-5">
      <SectionHeader
        icon={<LuFileText className="h-[18px] w-[18px]" />}
        title="자산 리포트"
        action={{ label: '전체보기' }}
      />
      <div className="mt-3 space-y-3">
        {reports.map((report) => {
          const Icon = report.type === '계약서' ? LuShield : LuFileText;
          return (
            <Card key={report.id} className="flex items-center gap-3 p-3.5">
              <div className="bg-brand-soft text-brand flex h-12 w-12 shrink-0 items-center justify-center rounded-xl">
                <Icon className="h-5 w-5" />
              </div>
              <div className="min-w-0 flex-1">
                <div className="flex flex-wrap items-center gap-1.5">
                  <Badge variant="secondary">{report.type}</Badge>
                  {report.autoGenerated && <Badge variant="outline">자동 생성</Badge>}
                </div>
                <h3 className="text-ink-900 mt-1.5 truncate text-[15px] font-bold">
                  {report.title}
                </h3>
                <div className="text-ink-400 mt-1.5 flex items-center gap-1.5 text-[12px]">
                  <LuClock className="h-3.5 w-3.5" />
                  <span>
                    {report.dateLabel} · {report.size}
                  </span>
                </div>
              </div>
              <button
                type="button"
                className="bg-ink-100 text-ink-500 hover:bg-ink-200 flex h-9 w-9 shrink-0 items-center justify-center rounded-full transition-colors"
              >
                <LuDownload className="h-4 w-4" />
              </button>
            </Card>
          );
        })}
      </div>
    </section>
  );
};
