import type { ComponentType } from 'react';
import { LuFileText, LuReceipt, LuShield } from 'react-icons/lu';
import type { DB } from '@mungsan/db';

import { SectionHeader } from '@/components/section-header';
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import { formatKst } from '@/lib/datetime/format-kst';
import { getCurrentUser } from '@/lib/auth/get-current-user';

import { getManageAssetReportsQuery } from '../queries/manage-asset-reports.query';
import { ReportDownloadButton } from './report-download-button';

// 리포트 종류 → 아이콘/라벨 (소비 컴포넌트 로컬 사전).
const TYPE_META: Record<
  DB.AssetReportType,
  { label: string; icon: ComponentType<{ className?: string }> }
> = {
  RETROSPECTIVE: { label: '회고 리포트', icon: LuFileText },
  SETTLEMENT: { label: '정산 서류', icon: LuReceipt },
  CONTRACT: { label: '계약서', icon: LuShield },
};

// 자산 리포트 — 현재 유저의 리포트 실목록. 종류별 아이콘 + 자동생성 배지 + 다운로드.
export async function AssetReportSection() {
  const user = await getCurrentUser();
  const reports = await getManageAssetReportsQuery(user.id);

  return (
    <section className="px-5">
      <SectionHeader icon={<LuFileText className="h-[18px] w-[18px]" />} title="자산 리포트" />
      <div className="mt-3 space-y-3">
        {reports.length === 0 ? (
          <p className="text-ink-400 py-8 text-center text-sm">아직 자산 리포트가 없습니다.</p>
        ) : (
          reports.map((report) => {
            const meta = TYPE_META[report.type];
            const Icon = meta.icon;
            return (
              <Card key={report.id} className="flex items-center gap-3 p-3.5">
                <div className="bg-brand-soft text-brand flex h-12 w-12 shrink-0 items-center justify-center rounded-xl">
                  <Icon className="h-5 w-5" />
                </div>
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-1.5">
                    <Badge variant="secondary">{meta.label}</Badge>
                    {report.autoGenerated && <Badge variant="outline">자동 생성</Badge>}
                  </div>
                  <h3 className="text-ink-900 mt-1.5 truncate text-[15px] font-bold">
                    {report.title}
                  </h3>
                  <p className="text-ink-400 mt-1.5 text-[12px]">
                    {formatKst(report.reportDate, 'yyyy.MM.dd')} ·{' '}
                    {formatFileSize(report.fileSizeBytes)}
                  </p>
                </div>
                <ReportDownloadButton />
              </Card>
            );
          })
        )}
      </div>
    </section>
  );
}

// 바이트 → 사람이 읽는 크기 표기(표시 전용).
function formatFileSize(bytes: number): string {
  if (bytes >= 1024 * 1024) return `${(bytes / 1024 / 1024).toFixed(1)}MB`;
  if (bytes >= 1024) return `${Math.round(bytes / 1024)}KB`;
  return `${bytes}B`;
}
